### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by will-metcher** [will-metcher/will-metcher.github.io#1]
- [x] Optimize images
- [x] Add more sorting algorithms
- [ ] Sort out landing page
- [ ] Sort out contact page
- [x] Add Dijkstra distance table
- [x] Make site responsive
- [ ] Fix Euler image load time
